# Pandas: ( Part 5 )
### - In this part we will solve some assignment questions in order to understand pandas in deep.

In [91]:
import pandas as pd
import numpy as np

In [92]:
a=list('abcdefghijklmnopqrstuvwxyz')
a

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [93]:
b=np.arange(26)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [94]:
c=dict(zip(a,b))
c

{'a': 0,
 'b': 1,
 'c': 2,
 'd': 3,
 'e': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [95]:
c1=pd.Series(a)
c2=pd.Series(b)
c3=pd.Series(c)
c1

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [96]:
c2

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [97]:
c3

a     0
b     1
c     2
d     3
e     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [98]:
c3.head()

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [99]:
#a b c c3

In [100]:
c4=pd.DataFrame(c3.unique().reshape(13,2))
c4

0   1
0    0   1
1    2   3
2    4   5
3    6   7
4    8   9
5   10  11
6   12  13
7   14  15
8   16  17
9   18  19
10  20  21
11  22  23
12  24  25

In [101]:
c3.head().to_frame().reset_index()    #sortcut 

index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4

In [102]:
a

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [103]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [104]:
#c1 c2
pd.concat([c1,c2],axis=1).head()

0  1
0  a  0
1  b  1
2  c  2
3  d  3
4  e  4

In [72]:
#c1
c1.name='alphabets'
c1.head()

0    a
1    b
2    c
3    d
4    e
Name: alphabets, dtype: object

In [108]:
d=pd.Series([1,2,3,4,5])
e=pd.Series([4,5,6,7,8])
d

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [109]:
e

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [114]:
d[d.isin(e)]

3    4
4    5
dtype: int64

In [115]:
d[-d.isin(e)]      #note Q6

0    1
1    2
2    3
dtype: int64

In [117]:
# Q7 starts

c6=np.union1d(d,e)
c7=np.intersect1d(d,e)
c6

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [118]:
c7

array([4, 5], dtype=int64)

In [120]:
c8=pd.Series(c6)
c9=pd.Series(c7)

c8[-c8.isin(c9)]

#end

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [122]:
f=pd.Series(np.random.normal(10,5,25))
f

0      7.139481
1     12.798544
2      4.536750
3      8.352290
4      1.830475
5      8.993881
6     11.108940
7     13.467891
8      3.177477
9      8.066484
10    12.147092
11     9.463749
12    12.202842
13    11.847514
14    13.527088
15    11.718771
16     4.356902
17     9.370900
18    15.838407
19    11.279803
20    10.496740
21    16.057497
22    22.755174
23    13.097705
24     6.463819
dtype: float64

In [123]:
f.describe()

count    25.000000
mean     10.403849
std       4.537124
min       1.830475
25%       8.066484
50%      11.108940
75%      12.798544
max      22.755174
dtype: float64

In [124]:
np.percentile(f,q=[0,25,50,75,100])

array([ 1.83047457,  8.0664837 , 11.10894001, 12.79854433, 22.75517397])

In [ ]:
# End...