# Pandas : ( Part 1 )
# Topics: Using Array and Dictionaries....
### - df=pd.Dataframe() , type() , .dtypes , .size , .shape , .index , .columns , .info() , .head(n) , .tail(n)
### - df[].unique , df[].unique() , df[].unique().reshape( , ) , df[].nunique() , df[].value_counts()  
### - df=pd.DataFrame( ,index=[....],columns=[....])
### - df[''].unique , df[''].unique() , df[''].unique().reshape() , df[''].nunique() , df[''].value_counts()  
### - .index=[.......]   (to change the index)
### - .columns=[......]   (to change the columns)
### - .rename(columns={'':''},index={'':''},inplace=True)  (inplace use to overwrite)
### - Indexing: df[''] or df. , df[['','']] , df.iloc[ , ] , df.iloc[:,[ , , ]] , df.loc['',''] , 
### - df.loc[df[''] > _ , ['','']] or df.loc[df.a > _ , ['','']]   ...( filtering and indexing)
### - .drop(labels=['',...],axis=1,inplace=True) or .drop(columns=['','',...])
### - .drop(index=[''])
### - pd.Series()  ...for list, dict, array it changes to series columns.

In [2]:
# lets start..

In [3]:
import numpy as np
import pandas as pd     # Importing pandas library as pd now whenever we need pandas library we will call it as pd

# Using Array

In [4]:
a=[1,2,3,3,4,5,5,6,7,7,8,9]

In [9]:
a1=np.array(a)
a2=a1.reshape(4,3)     # making 2D array to form dataframe
a2

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [10]:
a3=np.unique(a2).size        # this gives number of unique elments
a3

9

In [12]:
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9

In [73]:
type(df)

pandas.core.frame.DataFrame

In [74]:
df.size

12

In [75]:
df.shape

(4, 3)

In [76]:
df.index     #based on rows

RangeIndex(start=0, stop=4, step=1)

In [77]:
df.columns    #based on columns

RangeIndex(start=0, stop=3, step=1)

In [78]:
df.dtypes

0    int32
1    int32
2    int32
dtype: object

In [79]:
df.info()    # give type index coloums coloum wise elmnt dtype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
0    4 non-null int32
1    4 non-null int32
2    4 non-null int32
dtypes: int32(3)
memory usage: 128.0 bytes


In [80]:
df.head

<bound method NDFrame.head of    0  1  2
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9>

In [81]:
df.head(1)

0  1  2
0  1  2  3

In [82]:
df.tail()

0  1  2
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9

In [83]:
df.tail(3)

0  1  2
1  3  4  5
2  5  6  7
3  7  8  9

In [84]:
df[0].unique

<bound method Series.unique of 0    1
1    3
2    5
3    7
Name: 0, dtype: int32>

In [85]:
df[0].unique()      #gives uniqe elements in coloumn 1 and changes into array

array([1, 3, 5, 7], dtype=int64)

In [86]:
df[0].nunique()     # number of non repeted elements in coloum 1

4

In [87]:
df[2].value_counts()

7    1
5    1
3    1
9    1
Name: 2, dtype: int64

In [88]:
a2

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [89]:
df=pd.DataFrame(a2,index=['a','b','c','d'],columns=['x','y','z'])
df

x  y  z
a  1  2  3
b  3  4  5
c  5  6  7
d  7  8  9

In [90]:
df.index=['g','h','i','j']
df

x  y  z
g  1  2  3
h  3  4  5
i  5  6  7
j  7  8  9

In [91]:
df['y']

g    2
h    4
i    6
j    8
Name: y, dtype: int32

In [92]:
df[['y','z']]    #Indexing

y  z
g  2  3
h  4  5
i  6  7
j  8  9

In [93]:
# In this indexing is same as matrix some include
df.iloc[1,1]

4

In [94]:
df.iloc[1:3,1]

h    4
i    6
Name: y, dtype: int32

In [95]:
#we can also index by name of row and coloumns some change excluding wala concet not apply
df.loc['h','y']

4

In [96]:
df.loc[:,'z']

g    3
h    5
i    7
j    9
Name: z, dtype: int32

In [97]:
df

x  y  z
g  1  2  3
h  3  4  5
i  5  6  7
j  7  8  9

In [98]:
df.rename(columns={'x':'f'},index={'y':'b'},inplace=True)
df

f  y  z
g  1  2  3
h  3  4  5
i  5  6  7
j  7  8  9

In [99]:
df.rename(index={'h':'a'},inplace=True)
df

f  y  z
g  1  2  3
a  3  4  5
i  5  6  7
j  7  8  9

In [100]:
df.iloc[2,2]=12

In [101]:
df

f  y   z
g  1  2   3
a  3  4   5
i  5  6  12
j  7  8   9

In [102]:
df.drop(labels=['f'],axis=1,inplace=True)
df

y   z
g  2   3
a  4   5
i  6  12
j  8   9

# Using Dictionaries

In [48]:
m=dict(a=[1,2,3],b=[4,5,6],c=[7,8,9])
m

{'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

In [49]:
df1=pd.DataFrame(m)
df1

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [50]:
m=[1,2,3,4,5]      #using list changing list into series columns

In [51]:
pd.Series(m)    # S in capital

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [104]:
n=np.array(m)
n


array([1, 2, 3, 4, 5])

In [105]:
pd.Series(n)       # S is capital

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [54]:
d1=dict(a=1,b=2)       # using dict
d1

{'a': 1, 'b': 2}

In [52]:
pd.Series(d1)    # note when do by list we get index and her key name

a    1
b    2
dtype: int64

In [ ]:
# To Be Continued...