# Numpy : ( Part 2 Advanced )
### - np.setdiff1d( , ) , np.intersect1d( , ) , np.randon.uniform( , ,size=( , )) , swapping
### - changing value using filtering, indexing, etc.

In [122]:
import numpy as np

In [123]:
a=np.arange(0,10)

In [124]:
a              

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
b=a[1:10:2]     

In [121]:
a[a%2==1]     #alternte method of above

array([1, 3, 5, 7, 9])

In [118]:
b

array([1, 3, 5, 7, 9])

In [119]:
a10=[i for i in a if i%2==1]       # For odd   (alternate method)

In [120]:
np.array(a10)

array([1, 3, 5, 7, 9])

In [100]:
a=np.arange(0,10)

In [101]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a[1:10:2]=-1     

In [113]:
a[a%2==1]=-1   #alternate method of above

In [114]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
a.reshape(2,5)

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [55]:
d=np.arange(10).reshape(2,-1)

In [56]:
d      

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
d1=np.repeat(1,10).reshape(2,-1)

In [58]:
d1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [82]:
d2=d.ravel()

In [83]:
d3=d1.ravel()

In [87]:
d4=d2.tolist()

In [91]:
d4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
d5=d3.tolist()

In [90]:
d5

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [110]:
d6=d4[:5]+d5[:5]+d4[5:]+d5[5:]

In [111]:
d6

[0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1]

In [112]:
d7=np.array(d6)

In [113]:
d7

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [116]:
d7.reshape(2,10)     

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [36]:
p=np.array([1,2,3,2,3,4,3,4,5,6])

In [37]:
p

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [38]:
q=np.array([7,2,10,2,7,4,9,4,9,8])

In [39]:
q

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [40]:
r=set(p)

In [41]:
r1=set(q)

In [42]:
r

{1, 2, 3, 4, 5, 6}

In [43]:
r1

{2, 4, 7, 8, 9, 10}

In [44]:
r2=r&r1       # & operator to find common in set ,list

In [45]:
r2

{2, 4}

In [48]:
alternate_r2=np.intersect1d(p,q)       #alternate soln of Q11 below

In [49]:
alternate_r2

array([2, 4])

In [50]:
rt=np.array(r2)

In [51]:
rt       #created confusion resolved by list()

array({2, 4}, dtype=object)

In [52]:
r3=list(r2)    #uooer problem reslove

In [53]:
r3

[2, 4]

In [54]:
r4=np.array(r3)

In [55]:
r4       #Q11

array([2, 4])

In [56]:
x=np.array([1,2,3,4,5])

In [57]:
x

array([1, 2, 3, 4, 5])

In [58]:
y=np.array([5,6,7,8,9])

In [59]:
y

array([5, 6, 7, 8, 9])

In [60]:
x1=set(x)

In [61]:
y1=set(y)

In [62]:
x1

{1, 2, 3, 4, 5}

In [63]:
y1

{5, 6, 7, 8, 9}

In [64]:
y2=x1-y1       #Q12 remove itens that exist on another set

In [65]:
y2

{1, 2, 3, 4}

In [66]:
y4=list(y2)

In [67]:
y3=np.array(y4)

In [68]:
y3

array([1, 2, 3, 4])

In [70]:
alternate_y3=np.setdiff1d(x,y)      #Q12 alternt method

In [71]:
alternate_y3

array([1, 2, 3, 4])

In [69]:
k=np.array([1,2,3,2,3,4,3,4,5,6])

In [214]:
k

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [215]:
l=np.array([7,2,10,2,7,4,9,4,9,8])

In [216]:
l

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [287]:
np.where(k==l)         #Q13 where two elmt match 

(array([1, 3, 5, 7], dtype=int64),)

In [256]:
i=np.arange(9).reshape(3,3)

In [257]:
i

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [260]:
i[:,[0,1]]=i[:,[1,0]]     #Q16 swapping coloums 

In [261]:
i

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [14]:
import numpy as np

In [72]:
A=np.random.uniform(5,10,size=(5,3))      #Q20   

In [73]:
A

array([[6.27106586, 5.42783166, 7.02644666],
       [6.55199168, 7.20676204, 7.18765549],
       [7.03105449, 7.68305273, 9.3519439 ],
       [7.9432158 , 9.28449157, 8.11679952],
       [6.58299687, 9.50242719, 7.03568795]])

In [74]:
A.shape

(5, 3)

In [282]:
i

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [283]:
j=np.arange(9).reshape(3,3)

In [284]:
j

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [285]:
i==j       #Q3 boolean

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True]])

In [286]:
i!=j         #boolean 

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True, False]])

In [ ]:
# End...