# Numpy : ( Part 1 )
### It is an python library which is used for array
# Topics: Syntax,
### - 1D : np.array() , type() , .size , .shape , np.ndim() , sum() 
### - 2D : same as in 1D , .reshape( , ) 
### - np.arange( , ) , np.zeros(( , )) , np.ones(( , )) , np.eye() , np.linspace( , , ) ,
### - np.random.rand( , ) , np.random.randn( , ) , np.random.randint( , , ) , np.random.randint( , ,size=( , )) , 
### - Operators, Filtering, ravel() , np.uniqui().size

In [1]:
# Lets Start...

In [3]:
import numpy as np    # Import numpy as np means now we will use numpy library by calling np

In [4]:
a=[1,2,3,4,5]               # 1D starts

In [5]:
b=np.array(a)           # converts list into array

In [6]:
b                           # This is 1D Array

array([1, 2, 3, 4, 5])

In [7]:
c=[1,3,0.9]             # list contaning both int and float value

In [8]:
c1=np.array(c)

In [9]:
c1                      # note the output converted to float value

array([1. , 3. , 0.9])

In [10]:
type(b)                  #type function 

numpy.ndarray

In [11]:
b.size                   #Number of elements in array

5

In [12]:
b.shape                  #(R,C)

(5,)

In [13]:
np.ndim(b)                #Number of array dimension

1

In [14]:
sum(b)            # Rows addition

15

In [15]:
d=[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]             # 2D starts

In [16]:
e=np.array(d)             #Converts list into array

In [17]:
e         # This is 2D Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [18]:
type(e)

numpy.ndarray

In [19]:
e.size              # Number of elements in array

12

In [20]:
e.shape             #(R,C)   

(4, 3)

In [21]:
np.ndim(e)           #Number of dimension

2

In [22]:
sum(e)              #Rows addition

array([13, 17, 21])

In [23]:
e1=e.reshape(1,12)               #manage rows and coloum

In [24]:
e1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3]])

In [25]:
#Another method:

e2=np.arange(1,10)       # same as range function

In [26]:
e2                           #1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# To convert 1D to2D we use reshapping fuction as shown below

In [27]:
e3=e2.reshape(3,3)

In [28]:
e3                            #Coverted to 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
#now same process as done in 1D and 2D

In [30]:
np.zeros((2,3))                   #here row start from 1 and coloum start from 1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.eye(4)            # 4 indicates the size of matrics

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.linspace(0,10,5)      # divides into equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.linspace(1,10,16)

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6,  5.2,  5.8,  6.4,  7. ,
        7.6,  8.2,  8.8,  9.4, 10. ])

In [35]:
np.random.rand(3,4)        # gives random numbers here 3rows and 4coloums

array([[0.72723524, 0.53880532, 0.51665173, 0.69469517],
       [0.9983194 , 0.12026053, 0.4290134 , 0.44081148],
       [0.65989871, 0.28242875, 0.8045649 , 0.65604801]])

In [36]:
np.random.randn(3,4)        #for normal distribution part of statictics

array([[-0.71942215,  0.05524936, -0.13407635, -0.54018809],
       [-0.34061079, -0.69701807, -0.85642895,  1.72776153],
       [ 0.29501526,  2.27651116, -0.99051189,  2.05800512]])

In [37]:
np.random.randint(4,40,20)    #it will take any 20 int from 4(inclusive) and 20(exclusive)           #1D

array([25, 19, 11, 23, 25, 34, 22, 28, 13, 29, 32, 26, 34, 18, 39, 34, 20,
       26, 24, 10])

In [38]:
np.random.randint(0,50,size=(2,3))   #Here size is matrx[R,C]                                         #2D

array([[43,  7, 35],
       [24, 19, 33]])

In [39]:
e3[0,0]           #indexing [R,C]

1

In [40]:
e3[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
e3[2,1]

8

In [42]:
e3[1,2]

6

In [43]:
e3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
e3[1:,:2]

array([[4, 5],
       [7, 8]])

In [45]:
e3[1:,1:]

array([[5, 6],
       [8, 9]])

In [46]:
e3[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [47]:
e3[1:,]                #for empty coloums it will take all coloums

array([[4, 5, 6],
       [7, 8, 9]])

In [48]:
e3[,1:]                 #but for empty row it will raise error

SyntaxError: invalid syntax (<ipython-input-48-0ef86f9bf62e>, line 1)

In [ ]:
e3

In [ ]:
e3[[1,0],[2,2]]         #note

In [ ]:
e3[[1,2],[0,2]]          #note

In [ ]:
e3.sum()                 #Gives the addition of elements in array

In [69]:
import numpy as np

In [70]:
A=[1,2,3,4]

In [71]:
A1=np.array(A)

In [72]:
A1

array([1, 2, 3, 4])

In [73]:
A2=A1.reshape(2,2)

In [74]:
A2

array([[1, 2],
       [3, 4]])

In [75]:
B=[5,6,7,8]

In [76]:
B1=np.array(B)

In [77]:
B1

array([5, 6, 7, 8])

In [78]:
B2=B1.reshape(2,2)

In [79]:
B2

array([[5, 6],
       [7, 8]])

In [80]:
C=np.add(A2,B2)            # Addition of two matrix

In [81]:
C

array([[ 6,  8],
       [10, 12]])

In [82]:
C1=np.subtract(A2,B2)     # Subtraction of two matrix

In [83]:
C1

array([[-4, -4],
       [-4, -4]])

In [84]:
C3=np.multiply(A2,B2)     # Multipliction of two matrix

In [85]:
C3

array([[ 5, 12],
       [21, 32]])

In [86]:
C4=np.divide(A2,B2)       # Division of two matrix

In [87]:
C4

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [88]:
# Alternate method for above Operators

A2/B2      # A2-B2 , A2*B2 , A2+B2 , etc

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [89]:
# Condition checking

A2==B2

array([[False, False],
       [False, False]])

In [90]:
A2!=B2     # Condition checking

array([[ True,  True],
       [ True,  True]])

In [91]:
A2<B2      # Condition checking

array([[ True,  True],
       [ True,  True]])

In [92]:
A2>B2      # Condition checking

array([[False, False],
       [False, False]])

In [93]:
A2<2     # Condition checking

array([[ True, False],
       [False, False]])

In [94]:
B2>2     # Condition checking

array([[ True,  True],
       [ True,  True]])

# To convert any dimension to 1D we use .ravel() as shown below

In [95]:
A2.ravel()

array([1, 2, 3, 4])

# Filtering

In [96]:
A2

array([[1, 2],
       [3, 4]])

In [97]:
A2[A2<3]               # note filtering also convert 2D to 1d

array([1, 2])

In [98]:
A2[A2<5]

array([1, 2, 3, 4])

In [99]:
A2[A2==4]

array([4])

In [100]:
A2[A2!=4]

array([1, 2, 3])

In [101]:
np.unique(A2)           #Smlar to set

array([1, 2, 3, 4])

In [102]:
A2.size    #gives size of unique elements or we can wrie the two steps as np.unique(A2).size

4

In [ ]:
# To Be Continue In Next Part....