# Build My Own Artificial Neural Network From Scratch

## What’s a Neural Network?
### Most introductory texts to Neural Networks brings up brain analogies when describing them. Without delving into brain analogies, I find it easier to simply describe Neural Networks as a mathematical function that maps a given input to a desired output.
### Neural Networks consist of the following components
### - An input layer
### - An arbitrary amount of hidden layers
### - An output layer
### - A set of weights and biases between each layer, W and b
### - A choice of activation function for each hidden layer, σ. In this tutorial, we’ll use a Sigmoid activation function.

## Training the Neural Network

### Naturally, the right values for the weights and biases determines the strength of the predictions. The process of fine-tuning the weights and biases from the input data is known as training the Neural Network.
### Each iteration of the training process consists of the following steps:
### - Calculating the predicted output , known as feedforward
### - Adjusting the weights and biases, known as backpropagation

# Important Formulas : 
### --> sigmoid                    = 1/(1+np.exp(-x))      
### --> sigmoid_derivative = x*(1-x)
### --> error = output - predicted_output   
### --> Adjust_weights_by = error.input.sigmoid_derivative    
### Note - In above formulas np is numpy , exp is exponential and ( . ) is dot product and moreover there are many formulas and types of activation functions and loss functions ( i.e error ) but in this tutorial I will use this one for simplicity.

## Method - 01 
### ( This Method is Just for Clearing Concepts from Next Methods we wil build it systematically )

In [1]:
# Impoting required Libraries
import numpy as np

# Input Data
x = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

# Output Data
y = np.array([[0],
              [1],
              [1],
              [0]])


# Sigmoid function (One of the type of Activation function)
def sigmoid(x , deriv = False):
    
    if deriv == True:
        return (x*(1-x))     # We will active this in Back Propogation
    
    return 1/(1+np.exp(-x))  # We will active this in Forward Propogation


# Seed
np.random.seed(1)    # For Debugging

# Synapses
syn0 = 2*np.random.random((x.shape[1],4)) -1  # Here first argument is no. of input cols & second is no. nodes
syn1 = 2*np.random.random(y.shape) - 1        # Here argument is shape of output

# Training

for j in list(range(60000)):
    
    # Layers
    l0 = x                             # Input layer
    l1 = sigmoid(np.dot(l0, syn0))     # Hidden layer
    l2 = sigmoid(np.dot(l1, syn1))     # Output layer
    
    # Backpropagation
    l2_error = y - l2
    
    if j%10000 == 0:    # This will print the error rate in every 10000 training_iterations
        print('Error : ' + str(np.mean(np.abs(l2_error))))
        
    # Calculate deltas
    l2_delta = l2_error * sigmoid(l2 , deriv = True)
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * sigmoid(l1 , deriv = True)
    
    # Update our synapses
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    
print()
print('Output after Training')
print(l2)

Error : 0.49641003190272537
Error : 0.008584525653247155
Error : 0.005789459862507812
Error : 0.004629176776769985
Error : 0.0039587652802736475
Error : 0.0035101225678616744

Output after Training
[[0.00260572]
 [0.99672209]
 [0.99701711]
 [0.00386759]]


## Method - 02
### ( In this method we will consider that there is no hidden layers inputs is directly connected to output )
### ( In Next method we will drive into hidden layers too )

In [2]:
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        
        # Seed the random number generator
        np.random.seed(1)    # For debugging

        # Set synaptic weights to a 3x1 matrix, with values from -1 to 1 and mean 0
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
        
    def sigmoid(self, x, deriv = False):
        
        """
        The derivative of the sigmoid function used to
        calculate necessary weight adjustments (Back Propagation)
        """
        if deriv == True:
            return x * (1 - x)
        
        """
        Takes in weighted sum of the inputs and normalizes
        them through between 0 and 1 through a sigmoid function (Forward Propagation)
        """
        return 1 / (1 + np.exp(-x))
        
        
    def train(self, training_inputs, training_outputs, training_iterations):
        
        """
        We train the model through trial and error, adjusting the
        synaptic weights each time to get a better result
        """
        for neural_network in range(training_iterations):
            
            # Pass training set through the neural network
            output = self.think(training_inputs)
            
            # Calculate the error rate
            error = training_outputs - output

            # Multiply error by input and gradient of the sigmoid function
            # Less confident weights are adjusted more through the nature of the function
            #np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
            
            adjustments = np.dot(training_inputs.T, error * self.sigmoid(output , deriv = True)) 
            
            # Adjust synaptic weights
            self.synaptic_weights += adjustments
            
        print()
        print('Error : ' + str(np.mean(np.abs(error))))
        print()
        print('Outputs after training')
        print(output)

    def think(self, inputs):
        """
        Pass inputs through the neural network to get output
        """
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


if __name__ == "__main__":

    # Initialize the single neuron neural network
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights)

    # The training set, with 4 examples consisting of 3 input values and 1 output value
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T

    # Train the neural network
    neural_network.train(training_inputs, training_outputs, 60000)

    print()
    print("Synaptic weights after training: ")
    print(neural_network.synaptic_weights)
    
    print()
    print("Let's Predict...!")
    A = int(input("Input 1: "))
    B = int(input("Input 2: "))
    C = int(input("Input 3: "))
    
    print("New situation: input data = ", A, B, C)
    print("Output data: ")
    print(neural_network.think(np.array([A, B, C])))

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

Error : 0.0032161293267241654

Outputs after training
[[0.00390234]
 [0.99681554]
 [0.99740397]
 [0.00318168]]

Synaptic weights after training: 
[[11.49345763]
 [-0.2048909 ]
 [-5.54227641]]

Let's Predict...!
Input 1: 1
Input 2: 1
Input 3: 0
New situation: input data =  1 1 0
Output data: 
[0.99998748]


## Method - 03
### ( In this method we will consider that there is 1 hidden layer with 4 nodes )

In [3]:
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        # Seed the random number generator
        np.random.seed(1)    # For debugging

        # Set synaptic weights to a 3x1 matrix,
        # with values from -1 to 1 and mean 0
        #self.synaptic_weights = 2 * np.random.random((3, 1)) - 1
        self.synaptic_weights0 = 2*np.random.random((3,4)) - 1   # Here first argument is no. of input cols & second is no. nodes
        self.synaptic_weights1 = 2*np.random.random((4,1)) - 1   # Here argument is shape of output

    def sigmoid(self, x, deriv = False):
        
        """
        The derivative of the sigmoid function used to
        calculate necessary weight adjustments
        """
        if deriv == True:
            return x * (1 - x)
        
        """
        Takes in weighted sum of the inputs and normalizes
        them through between 0 and 1 through a sigmoid function
        """
        return 1 / (1 + np.exp(-x))


    def train(self, training_inputs, training_outputs, training_iterations):
        """
        We train the model through trial and error, adjusting the
        synaptic weights each time to get a better result
        """
        for neural_network in range(training_iterations):
            # Pass training set through the neural network
            hidden = self.think(training_inputs)[0]
            output = self.think(training_inputs)[1]
            inputs = self.think(training_inputs)[2]
    
            # Calculate the error rate
            error = training_outputs - output

            # Multiply error by input and gradient of the sigmoid function
            # Less confident weights are adjusted more through the nature of the function
            
            output_delta = error * self.sigmoid(output, deriv = True)
            error_hidden = output_delta.dot(self.synaptic_weights1.T)    # hidden layer error
            hidden_delta = error_hidden * self.sigmoid(hidden, deriv = True)
            
            adjustments1 = np.dot(hidden.T, output_delta)
            adjustments0 = np.dot(inputs.T, hidden_delta)
            
            # Adjust synaptic weights
            self.synaptic_weights1 += adjustments1
            self.synaptic_weights0 += adjustments0
            
        print()
        print('Error : ' + str(np.mean(np.abs(error))))
        print()
        print('Outputs after training')
        print(output)
        
    def think(self, inputs):
        """
        Pass inputs through the neural network to get output
        """
        inputs = inputs.astype(float)
        hidden = self.sigmoid(np.dot(inputs, self.synaptic_weights0))
        output = self.sigmoid(np.dot(hidden, self.synaptic_weights1))
        
        return hidden , output , inputs


if __name__ == "__main__":

    # Initialize the single neuron neural network
    neural_network = NeuralNetwork()

    print("Random starting synaptic weights: ")
    print(neural_network.synaptic_weights0)
    print(neural_network.synaptic_weights1)

    # The training set, with 4 examples consisting of 3 input values and 1 output value
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T

    # Train the neural network
    neural_network.train(training_inputs, training_outputs, 10000)

    print()
    print("Synaptic weights after training: ")
    print(neural_network.synaptic_weights0)
    print(neural_network.synaptic_weights1)
    
    print()
    print("Let's Predict...!")
    A = int(input("Input 1: "))
    B = int(input("Input 2: "))
    C = int(input("Input 3: "))
    
    print("New situation: input data = ", A, B, C)
    print("Output data: ")
    print(neural_network.think(np.array([A, B, C]))[1])

Random starting synaptic weights: 
[[-0.16595599  0.44064899 -0.99977125 -0.39533485]
 [-0.70648822 -0.81532281 -0.62747958 -0.30887855]
 [-0.20646505  0.07763347 -0.16161097  0.370439  ]]
[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]
 [ 0.34093502]]

Error : 0.005002695580586832

Outputs after training
[[0.00510229]
 [0.99437164]
 [0.99493875]
 [0.00421887]]

Synaptic weights after training: 
[[-2.45237664  4.24246073 -4.51602703  0.20084556]
 [-0.37852498 -0.46226218  0.03227375 -0.22607559]
 [ 0.70578881 -1.40848121  1.82311171  0.44840252]]
[[-2.73124389]
 [ 6.00597609]
 [-5.78228268]
 [ 0.57952083]]

Let's Predict...!
Input 1: 0
Input 2: 1
Input 3: 1
New situation: input data =  0 1 1
Output data: 
[0.00421865]


## ...END...